BEGIN TRANSACTION;
CREATE TABLE pacer_cases (court_id TEXT NOT NULL, case_id INTEGER, case_number TEXT, case_type TEXT, case_title TEXT, date_filed TEXT, jurisdiction_type TEXT, case_link TEXT, case_summary TEXT, parties TEXT, attorney TEXT, PRIMARY KEY (court_id, case_id));
INSERT INTO "pacer_cases" VALUES('cobk',480643,'2','mp','Smith and Smith','2022-01-22','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?2','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?2','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?2');
INSERT INTO "pacer_cases" VALUES('tc1bk',43698,'10006','bk','Smith Family Farms LLC','2023-04-05','Bankruptcy','https://ecf.tc1b.aztc.uscourts.gov/cgi-bin/iqquerymenu.pl?43698','https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?10006','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?10006','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?10006');
INSERT INTO "pacer_cases" VALUES('azttdc',84670,'1619','cv','SMITH','2015-06-25','Civil','https://ecf.tc1d.aztc.uscourts.gov/cgi-bin/iqquerymenu.pl?84670','https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?1619','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?1619','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?1619');
INSERT INTO "pacer_cases" VALUES('azttdc',92944,'84','cv','SMITH','2017-03-23','Civil','https://ecf.tc1d.aztc.uscourts.gov/cgi-bin/iqquerymenu.pl?92944','https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?84','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?84','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?84');
INSERT INTO "pacer_cases" VALUES('cmmbk',137945,'1946','bk','Smith','2015-11-09','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?1946','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?1946','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?1946');
INSERT INTO "pacer_cases" VALUES('cmmbk',140330,'2360','bk','smith','2016-02-25','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?2360','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?2360','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?2360');
INSERT INTO "pacer_cases" VALUES('cmmbk',141918,'99999','bk','Smith','2017-02-23','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?99999','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?99999','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?99999');
INSERT INTO "pacer_cases" VALUES('cmmbk',142042,'5806','bk','Smith','2017-03-22','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?5806','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?5806','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?5806');
INSERT INTO "pacer_cases" VALUES('cmmbk',142046,'5810','bk','Smith','2017-03-23','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?5810','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?5810','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?5810');
INSERT INTO "pacer_cases" VALUES('cmmbk',142047,'5811','bk','Smith','2017-03-23','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?5811','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?5811','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?5811');
INSERT INTO "pacer_cases" VALUES('cmmbk',142048,'5812','bk','Smith','2017-03-23','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?5812','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?5812','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?5812');
INSERT INTO "pacer_cases" VALUES('cmmbk',142049,'5813','bk','Smith','2017-03-23','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?5813','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?5813','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?5813');
INSERT INTO "pacer_cases" VALUES('cmmbk',142055,'5819','bk','Smith','2017-03-24','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?5819','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?5819','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?5819');
INSERT INTO "pacer_cases" VALUES('tc4bk',83898,'19','bk','Smith','2019-07-31','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?19','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?19','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?19');
INSERT INTO "pacer_cases" VALUES('tc4bk',1037,'69','bk','smith','2001-05-07','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?69','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?69','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?69');
INSERT INTO "pacer_cases" VALUES('tc4bk',1056,'80','bk','smith','2001-06-14','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?80','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?80','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?80');
INSERT INTO "pacer_cases" VALUES('tc4bk',13785,'2424','ap','Smith','2001-02-14','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?2424','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?2424','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?2424');
INSERT INTO "pacer_cases" VALUES('tc4bk',13786,'2424','ap','Smith','2001-02-14','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?2424','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?2424','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?2424');
INSERT INTO "pacer_cases" VALUES('cobk',144299,'10061','bk','Smith & Jones, Inc.','2004-01-04','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?10061','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?10061','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?10061');
INSERT INTO "pacer_cases" VALUES('tc4bk',17752,'266','bk','Smith & Sisters Trucking','2009-06-17','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?266','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?266','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?266');
INSERT INTO "pacer_cases" VALUES('tcebk',3058,'382','bk','Smith & Sisters Trucking','2002-07-09','Bankruptcy','https://ecf.tceb.aztc.uscourts.gov/cgi-bin/iqquerymenu.pl?3058','https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?382','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?382','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?382');
INSERT INTO "pacer_cases" VALUES('tc4bk',3040,'366','bk','Smith & Sons','2002-07-09','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?366','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?366','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?366');
INSERT INTO "pacer_cases" VALUES('cmmbk',134110,'1473','ap','Smith and America Express','2011-09-22','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?1473','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?1473','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?1473');
INSERT INTO "pacer_cases" VALUES('tc4bk',340,'1049','ap','Smith and American Express','2000-10-25','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?1049','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?1049','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?1049');
INSERT INTO "pacer_cases" VALUES('cobk',475827,'1285','ap','Smith and American Express Centurion Bank','2018-09-06','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?1285','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?1285','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?1285');
INSERT INTO "pacer_cases" VALUES('tc4bk',16971,'146','ap','Smith and Anderson','2008-10-08','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?146','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?146','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?146');
INSERT INTO "pacer_cases" VALUES('tc4bk',17119,'32345','ap','Smith and Anderson','2008-12-11','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?32345','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?32345','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?32345');
INSERT INTO "pacer_cases" VALUES('tc4bk',17219,'119','ap','SMITH and Anderson','2008-12-22','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?119','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?119','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?119');
INSERT INTO "pacer_cases" VALUES('tc4bk',17597,'106','ap','SMITH and Anderson','2009-06-09','Bankruptcy',NULL,'https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?106','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?106','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?106');
INSERT INTO "pacer_cases" VALUES('tc1bk',15122,'129','ap','Smith and Baffert','2007-09-18','Bankruptcy','https://ecf.tc1b.aztc.uscourts.gov/cgi-bin/iqquerymenu.pl?15122','https://ecf.casd.uscourts.gov/cgi-bin/qrySummary.pl?129','https://ecf.casd.uscourts.gov/cgi-bin/qryParties.pl?129','https://ecf.casd.uscourts.gov/cgi-bin/qryAttorneys.pl?129');
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    permission TEXT CHECK(permission IN ('admin', 'edit', 'browse')) NOT NULL
);
INSERT INTO "users" VALUES(1,'colepopkin','e33c3a4c1483cab0ef42023cc4b4ad783d1c8b6f2a7c62de5491a77767d85530','admin');
INSERT INTO "users" VALUES(2,'kenpopkin','5ec87f3bccf279784ba51d06f2eff3defa28434be6595a6767666e10b75c968f','edit');
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('users',3);
COMMIT;
